FROM python:3.8.20-slim

# System deps
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Install MLflow
RUN pip install --no-cache-dir mlflow

# Create a non-root user (optional but recommended)
RUN useradd --create-home mlflowuser
USER mlflowuser

WORKDIR /app

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///app/mlflow/mlflow.db", "--default-artifact-root", "/app/artifacts", "--host", "0.0.0.0", "--port", "5000"]
