FROM python:3.8.20-slim

WORKDIR /app

# Install MLflow
RUN pip install --no-cache-dir mlflow

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///app/mlflow/mlflow.db", "--default-artifact-root", "/app/artifacts", "--host", "0.0.0.0", "--port", "5000"]
