raw_data_path: "data/raw/data.csv"
processed_data_path: "data/processed/data_cleaned.csv"

columns_to_drop:
  - emp_title
  - emp_length
  - title
  - issue_d
  - grade

numeric_transformations:
  - column_name: term
    pattern: (\d+)
    default_value: 0
  - column_name: int_rate
    pattern: (\d+(\.\d+)?)
    remove_chars: '%'
    default_value: 0
  - column_name: revol_util
    pattern: (\d+(\.\d+)?)
    remove_chars: '%'
    default_value: 0

outlier_cols:
  annual_inc: 250000
  dti: 50
  open_acc: 40
  total_acc: 80
  revol_util: 120
  revol_bal: 250000

outlier_quantile: 0.95

date_columns:
  earliest_cr_line: "%b-%Y"

categorical_columns:
  - sub_grade
  - verification_status
  - purpose
  - initial_list_status
  - application_type
  - home_ownership

zip_code_column: address

columns_to_drop_additional:
  - zip_code

strategies:
  - simple
  - stratified